### ISSUE TITLE
Not working in outlook 2016

### ISSUE THREAD

**Issue by polytan02** [KyleWJohnston/outlook-move-to-thread#2] opened 2019-07-09 10:50 UTC
Hello,

I have been thinking of such macro for long time !
On my side, I'm on outlook 2016 and I try to move emails from inbox to subfolder of the same inbox.

I did multiple tries, but all I get is "no folders found" whereas the conversation view clearly shows the firsts emails being in a subfolder.

**Comment by k4j8** [comment] 2019-07-09 20:22
Despite only being the second issue opened, this turned out to be a duplicate of issue #1.

**Closed as completed by k4j8** 2019-07-09 20:22 UTC
Labels: duplicate
